xgb_Classifier:
  name: 'xgb_Classifier'
  params:
    learning_rate: [0.1, 0.2]
    gamma : [0.5, 0.6]
    reg_alpha : [0.1, 0.6]
    reg_lambda : [1, 2]
    max_depth : [7,8]
    subsample : [0.7, 0.8]
    scale_pos_weight : [1, 2]
    colsample_bytree : [0.5, 0.4]
SGDClassifier:
  name: 'SGDClassifier'
  params:
    alpha: [0.01, 0.03]
    max_iter: [10, 9]
    penalty : ['l2', 'l1']
    loss : ['modified_huber']
RandomForestClassifier:
  name: 'RandomForestClassifier'
  params:
    n_estimators: [50, 75, 100, 150]
    max_depth: [5, 10, 15, 20]
    min_samples_split: [2, 5, 10, 15]
    min_samples_leaf: [1, 2, 4, 6]
    criterion: ['gini', 'entropy']